WebApplication5/Controllers/ChiTietSachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class ChiTietSachController : Controller
    {
        BookContext db = new BookContext();
        public static List<Sach> listCTHD = new List<Sach>();
        // GET: ChiTietSach
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Index(int id)
        {

            
            var db = new BookContext();
            if (db.Sach.Find(id) == null)
            {
                return HttpNotFound();
            }
            if (id == null)
                return HttpNotFound();
            Session["ListCTS"] = db.Sach.Find(id);
            Session["ListCungChuDe"] = GetListCungChuDe(db.Sach.Find(id).MaChuDe,id);
            db.Sach.Find(id).LuotXem++;
            db.SaveChanges();
            return View("Index");
            

        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult ThemGioHang(int idSach)
        {
            if (Session["KhachHang"] == null)
            {
                return View("../DangNhap/Index");
            }
            else
            {
                var db = new BookContext();
                var tk = Session["KhachHang"] as KhachHang;
                var hd = db.HoaDon.Where(i => i.DaThanhToan == false && i.MaKH == tk.MaKH).FirstOrDefault();
                if (hd == null)
                {
                    HoaDon newHd = new HoaDon();
                    newHd.MaKH = tk.MaKH;
                    newHd.NgayTao = DateTime.Today;
                    newHd.DaThanhToan = false;
                    newHd.flag = true;
                    newHd.TongTien = 0;
                    newHd.SDT = "";
                    newHd.DiaChi = "";
                    db.HoaDon.Add(newHd);
                    db.SaveChanges();

                    ChiTietHoaDon newCTHD = new ChiTietHoaDon();
                    newCTHD.MaSach = idSach;
                    newCTHD.MaDonHang = newHd.MaDonHang;
                    newCTHD.SoLuong = 1;
                    newCTHD.ThanhTien = db.Sach.Find(idSach).GiaBan * newCTHD.SoLuong;
                    newCTHD.flag = true;
                    db.ChiTietHoaDon.Add(newCTHD);
                    db.SaveChanges();
                }
                else
                {
                    var listCTHD = db.ChiTietHoaDon.Where(i => i.MaDonHang == hd.MaDonHang).ToList();
                    int pb = 0;
                    foreach (var item in listCTHD)
                    {
                        if (item.MaSach == idSach)
                        {
                            pb = 1;
                            var cthd = db.ChiTietHoaDon.Find(item.MaCTDH);
                            cthd.SoLuong = cthd.SoLuong + 1;
                            if (cthd.SoLuong > db.Sach.Find(idSach).SoLuongTon)
                            {
                                ViewBag.Add = "Add Unsuccessfully";
                                return View("Index");
                            }
                            else
                            {
                                cthd.ThanhTien = db.Sach.Find(idSach).GiaBan * cthd.SoLuong;
                                db.SaveChanges();
                                break;
                            }
                        }
                    }
                    if (pb == 0)
                    {
                        ChiTietHoaDon newCTHD = new ChiTietHoaDon();
                        newCTHD.MaSach = idSach;
                        newCTHD.MaDonHang = hd.MaDonHang;
                        newCTHD.SoLuong = 1;
                        newCTHD.ThanhTien = db.Sach.Find(idSach).GiaBan * newCTHD.SoLuong;
                        newCTHD.flag = true;
                        db.ChiTietHoaDon.Add(newCTHD);
                        db.SaveChanges();
                    }
                }
                ViewBag.Add = "Add successfully";
                return View("Index");
            }
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult MuaNgay(int idSach)
        {
            if (Session["KhachHang"] == null)
            {
                return View("../DangNhap/Index");
            }
            else
            {
                var db = new BookContext();
                var tk = Session["KhachHang"] as KhachHang;
                var hd = db.HoaDon.Where(i => i.DaThanhToan == false && i.MaKH == tk.MaKH).FirstOrDefault();
                if (hd == null)
                {
                    HoaDon newHd = new HoaDon();
                    newHd.MaKH = tk.MaKH;
                    newHd.NgayTao = DateTime.Today;
                    newHd.DaThanhToan = false;
                    newHd.flag = true;
                    newHd.TongTien = 0;
                    newHd.SDT = "";
                    newHd.DiaChi = "";
                    db.HoaDon.Add(newHd);
                    db.SaveChanges();

                    ChiTietHoaDon newCTHD = new ChiTietHoaDon();
                    newCTHD.MaSach = idSach;
                    newCTHD.MaDonHang = newHd.MaDonHang;
                    newCTHD.SoLuong = 1;
                    newCTHD.ThanhTien = db.Sach.Find(idSach).GiaBan * newCTHD.SoLuong;
                    newCTHD.flag = true;
                    db.ChiTietHoaDon.Add(newCTHD);
                    db.SaveChanges();
                }
                else
                {
                    var listCTHD = db.ChiTietHoaDon.Where(i => i.MaDonHang == hd.MaDonHang).ToList();
                    int pb = 0;
                    foreach (var item in listCTHD)
                    {
                        if (item.MaSach == idSach)
                        {
                            pb = 1;
                            var cthd = db.ChiTietHoaDon.Find(item.MaCTDH);
                            cthd.SoLuong = cthd.SoLuong + 1;
                            if (cthd.SoLuong > db.Sach.Find(idSach).SoLuongTon)
                            {
                                ViewBag.Add = "Add Unsuccessfully";
                                return View("Index");
                            }
                            else
                            {
                                cthd.ThanhTien = db.Sach.Find(idSach).GiaBan * cthd.SoLuong;
                                db.SaveChanges();
                                break;
                            }
                        }
                    }
                    if (pb == 0)
                    {
                        ChiTietHoaDon newCTHD = new ChiTietHoaDon();
                        newCTHD.MaSach = idSach;
                        newCTHD.MaDonHang = hd.MaDonHang;
                        newCTHD.SoLuong = 1;
                        newCTHD.ThanhTien = db.Sach.Find(idSach).GiaBan * newCTHD.SoLuong;
                        newCTHD.flag = true;
                        db.ChiTietHoaDon.Add(newCTHD);
                        db.SaveChanges();
                    }
                }
                ViewBag.Add = "Add successfully";
                return RedirectToAction("Index","GioHang");
            }
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public List<Sach> GetListCungChuDe(int idChuDe,int idSach)
        {
            var db = new BookContext();
            return db.Sach.Where(i => i.flag == false && i.MaChuDe == idChuDe && i.MaSach != idSach).Take(4).ToList();
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public void Dem(KhachHang kh)
        {
            HoaDon hd = db.HoaDon.Where(i => i.DaThanhToan == false && i.MaKH == kh.MaKH).FirstOrDefault();
            int soluong = 0;
            foreach (var item in db.ChiTietHoaDon.Where(i=>i.flag==false && i.MaDonHang==hd.MaDonHang).ToList())
            {
                soluong += item.SoLuong;
            }
            Session["SL"] = soluong;
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        [HttpPost]
        public ActionResult ThemSach(int id, int soluong = 1)
        {

            KhachHang kh = new KhachHang();
            kh = Session["KhachHang"] as KhachHang;
            if (kh == null)
            {
                return RedirectToAction("Index", "DangNhap");
            }
            else
            {
                HoaDon hd = db.HoaDon.Where(i => i.MaKH == kh.MaKH && i.DaThanhToan == false).FirstOrDefault();
                if (hd == null)
                {
                    HoaDon newHD = new HoaDon();
                    newHD.MaKH = kh.MaKH;
                    newHD.DaThanhToan = false;
                    newHD.NgayTao = DateTime.Now;
                    newHD.TongTien = 0;
                    newHD.flag = false;
                    db.HoaDon.Add(newHD);
                    db.SaveChanges();
                    ChiTietHoaDon ctHD = new ChiTietHoaDon();
                    ctHD.MaDonHang = newHD.MaDonHang;
                    ctHD.MaSach = id;
                    ctHD.SoLuong = soluong;
                    ctHD.ThanhTien = db.Sach.Find(id).GiaBan * ctHD.SoLuong;
                    db.HoaDon.Find(newHD.MaDonHang).TongTien = ctHD.ThanhTien;
                    ctHD.flag = false;
                    db.ChiTietHoaDon.Add(ctHD);
                    db.SaveChanges();
                    Dem(kh);
                    return RedirectToAction("Index", "GioHang");
                }
                else
                {
                    ChiTietHoaDon ctHD = db.ChiTietHoaDon.Where(i => i.MaDonHang == hd.MaDonHang && i.flag == false && i.MaSach == id).FirstOrDefault();
                    if (ctHD == null)
                    {
                        ChiTietHoaDon newCtHD = new ChiTietHoaDon();

WebApplication5/Views/ChiTietSach/Index.cshtml
@using WebApplication5.scripts;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
@if (ViewBag.Add != null)
{
    <script type="text/javascript" charset="utf-8">
        window.onload = function () {
        alert("@ViewBag.Add");
    }
    </script>
}
<div class="breadcrumb">
    <div class="container">
        <a class="breadcrumb-item" href="~/Home/Index">Trang Chủ</a>
        <span class="breadcrumb-item active">Thông tin sản phẩm</span>
    </div>
</div>
<section class="product-sec">
    @{ var Sach = Session["ListCTS"] as WebApplication5.Models.Sach;}
    <div class="container">
        <h1>@Sach.TenSach</h1>
        <div class="row">
            <div class="col-md-6 slider-sec">
                <!-- main slider carousel -->
                <div id="myCarousel" class="carousel slide">
                    <!-- main slider carousel items -->
                    <div class="carousel-inner">
                        <div class="active item carousel-item" data-slide-number="0">
                            <img src="~/UploadedFiles/@Sach.AnhBia" style="height: 427px;margin-left: 60px;margin-top: 5px;" class="img-fluid">
                        </div>
                    </div>
                    <!-- main slider carousel nav controls -->

                </div>
                <!--/main slider carousel-->
            </div>
            <div class="col-md-6 slider-content">
                <p style="font-family: sans-serif;font-size:large">@Sach.MoTa</p>

                <ul>

                    <li>
                        <span class="name">Giá</span><span class="clm">:</span>
                        <span class="price final">@Sach.GiaBan VND</span>
                    </li>
                    <li>
                        <span class="name">Còn hàng</span><span class="clm">:</span>
                        <span class="price final">@Sach.SoLuongTon</span>
                    </li>
                </ul>
                <div class="btn-sec">
                    @if (Sach.SoLuongTon > 0)
                    {
                        <div class="btn-sec">
                            <button onclick="location.href='@Url.Action("ThemGioHang", "ChiTietSach",new {idSach=Sach.MaSach})'" class="btn">Thêm vào giỏ hàng</button>
                            <button onclick="location.href='@Url.Action("MuaNgay", "ChiTietSach",new {idSach=Sach.MaSach})'" class="btn yellow">Mua ngay</button>
                        </div>}
                    else
                    {
                        <div class="btn-sec">
                            <button disabled class="btn ">Thêm giỏ hàng</button>
                            <button disabled class="btn yellow">Mua ngay</button>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<section class="related-books">
    <div class="container">
        <h2>Chắc bạn cũng sẽ thích những cuốn sách này</h2>
        <div class="recomended-sec">
            @{ var SachCungChuDe = Session["ListCungChuDe"] as List<WebApplication5.Models.Sach>;}
            <div class="row">
                @if (SachCungChuDe != null)
                {
                    foreach (var item in SachCungChuDe)
                    {
                        <div class="col-lg-3 col-md-6">
                            <div class="item">
                                <img src="~/UploadedFiles/@item.AnhBia" alt="img" style="height:250px;width:200px">
                                <h3>@StringExtension.opimizeName(item.TenSach, 20)</h3>
                                <h6><span class="price">@item.GiaBan VND</span></h6>
                                <div class="hover">
                                    <a href="~/ChiTietSach/Index/@item.MaSach">
                                        <span><i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
                                    </a>

                                </div>
                            </div>
                        </div>
                    }
                }


            </div>
        </div>
    </div>
</section>