WebApplication5/Controllers/TheLoaiController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    public class TheLoaiController : Controller
    {
        // GET: TheLoai
        BookContext db = new BookContext();
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Index()
        {
            
            var db = new BookContext();
            return View(db.ChuDe.Where(x=>x.flag==false).ToList());
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult KetQua(int? id, int? page)
        {
            if (id == null)
                return HttpNotFound();
            else
            {
                ViewBag.MaSach = id;
                ViewBag.TenTheLoai = db.ChuDe.Find(id).TenChuDe;
                return View(db.Sach.Where(x => x.MaChuDe == id && x.flag==false).OrderByDescending(x => x.NgayCapNhat).ToPagedList(page ?? 1, 6));
            }
        }
    }
}

WebApplication5/Views/TheLoai/Index.cshtml
@model List<WebApplication5.Models.ChuDe>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<style>
    .container {
        font-family: sans-serif;
        width: 1200px;
        height: auto;
        margin: auto;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.09);
    }

    .theLoais {
        display: grid;
        grid-template-columns: auto auto auto auto;
        grid-column-gap: 50px;
        grid-row-gap: 20px;
        justify-content: center;
        padding: 20px;
    }

        .theLoais a {
            text-decoration: none;
            color: white;
        }

            .theLoais a:hover .theloai {
                background-color: #00b550;
            }

    .theloai {
        text-wrap: normal;
        background-color: #159c51;
        height: 50px;
        width: 150px;
        text-align: center;
        line-height: 50px;
        position: relative;
        box-shadow: 0 9px 15px -4px rgba(0, 0, 0, 0.1), 0 0 0 0 white, 10px 0 15px -4px rgba(0, 0, 0, 0.1), 0 0 0 0 white;
    }
</style>
<div class="container">
    <div class="theLoais">
        @{
            foreach (var item in Model)
            {
                <a href="/TheLoai/KetQua/?id=@item.MaChuDe&page=1">
                    <div class="theloai">
                        @item.TenChuDe
                    </div>
                </a>

            }
        }
    </div>
</div>

WebApplication5/Views/TheLoai/KetQua.cshtml
@using WebApplication5.ViewModel;
@using WebApplication5.scripts;
@using PagedList.Mvc
@model PagedList.IPagedList<WebApplication5.Models.Sach>
@{
    ViewBag.Title = "KetQua";
    Layout = "~/Views/Shared/Layout.cshtml";
    int id = ViewBag.MaSach;
}
<style>
    .container {
        font-family: sans-serif;
        width: 1200px;
        height: auto;
        margin: auto;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.09);
    }

    .theLoais {
        display: grid;
        grid-template-columns: auto auto auto;
        grid-gap: 20px;
        justify-content: space-between;
        padding: 20px;
    }

    .theloai {
        position: relative;
        width: 360px;
        height: 202px;
        box-shadow: 0 9px 15px -4px rgba(0, 0, 0, 0.1), 0 0 0 0 white, 10px 0 15px -4px rgba(0, 0, 0, 0.1), 0 0 0 0 white;
    }

        .theloai img {
            max-width: 140px;
            max-height: 190px;
            display: inline-block;
            margin-top: 6px;
        }

    .theLoais .info {
        word-wrap: break-word;
        text-decoration: none;
        width: 200px;
        float: right;
    }

    .info {
        padding: 10px;
    }

        .info a {
            text-decoration: none;
            color: black;
        }

            .info a:hover {
                color: rgb(24, 160, 103);
            }

        .info .btn-addCart {
            position: absolute;
            right: 1%;
            bottom: 2%;
            background: green;
            height: 50px;
            line-height: 50px;
            border-radius: 5px;
            width: 120px;
            text-align: center;
        }

            .info .btn-addCart:hover {
                background: rgb(26, 173, 26);
            }

            .info .btn-addCart a {
                color: white;
                display: block;
            }

    ul {
        list-style-type: none;
    }

    li {
        margin-left: 5px;
        display: inline-block;
        list-style-type: none;
    }
</style>
<div class="container">
    <h1 style="font-size:1.5em; text-transform:uppercase; margin-top:10px;">Thể loại: @ViewBag.TenTheLoai</h1>
</div>

<div class="container">
    <div class="theLoais">
        
        @{
            foreach (var item in Model)
            {
                var img = item.AnhBia;
                <div class="theloai">
                    <img src="~/UploadedFiles/@img" alt="">
                    <div class="info">
                        <h3><a href="/ChiTietSach/Index/@item.MaSach">@StringExtension.opimizeName(item.TenSach, 27)</a></h3>
                        <p>Tác giả: @SachMoiViewModel.GetTenTacGia(item.MaTacGia)</p>
                        <p>Giá tiền: @item.GiaBan</p>
                    </div>
                </div>
            }
        }
        

    </div>
</div>
<div class="container">
    <ul>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
        <li id="numPages">@Html.PagedListPager(Model, page => Url.Action("KetQua", "TheLoai", new { id, page }))</li>
    </ul>
</div>